import { chromium } from 'playwright';
const errs=[];const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});
await ctx.addInitScript(()=>{const real=Date;const off=new real('2026-10-09T02:10:00-05:00').getTime()-real.now();class D extends real{constructor(...a){super(...(a.length?a:[real.now()+off]))}static now(){return real.now()+off}};window.Date=D});
const pg=await ctx.newPage();pg.on('pageerror',e=>errs.push(e.message));
await pg.route('**/*',r=>{const u=r.request().url();return u.startsWith('file:')?r.continue():r.abort()});
await pg.goto('file:///home/user/marea/public/index.html');await pg.evaluate(()=>localStorage.clear());await pg.reload();await pg.waitForTimeout(400);
await pg.fill('#lced','0990000001');await pg.click('#lbtn');await pg.waitForSelector('.hh');
// v51: sin opciones de la app; hay un ejemplo y cada quien escribe la suya
console.log('bienvenida:',await pg.locator('.bienv').count(),'· ejemplo visible:',await pg.locator('.voto-ej').count(),'· opciones:',await pg.locator('#votoAlm button.voto-o').count());
await pg.fill('#almIn','Encocado en Quinindé');await pg.click('#votoAlm >> text=Agregar');await pg.waitForTimeout(400);
await pg.fill('#almIn','Pollo asado en La Concordia');await pg.press('#almIn','Enter');await pg.waitForTimeout(400);
console.log('opciones después:',await pg.locator('#votoAlm button.voto-o').count(),'· ejemplo ya no:',await pg.locator('.voto-ej').count()===0);
await pg.locator('#votoAlm button.voto-o:has-text("Encocado")').click();await pg.waitForTimeout(300);
console.log('un solo voto (en Encocado):',await pg.evaluate(()=>EVENTOS.filter(esAlmuerzoCamino).map(e=>e.titulo.slice(0,12)+':'+votosDe(e.id).length).join(' ')),'·',await pg.locator('#votoAlm .muted.tiny').first().innerText());
await pg.fill('#almIn','encocado en quininde');await pg.click('#votoAlm >> text=Agregar');await pg.waitForTimeout(300);
console.log('no duplica:',await pg.locator('#votoAlm button.voto-o').count()===2,'· en Mi día:',await pg.locator('.md-vt').count());
await pg.locator('.bienv').scrollIntoViewIfNeeded();await pg.screenshot({path:'/tmp/claude-0/-home-user/5853f958-644c-5d2f-baa4-3130bae7435e/scratchpad/bienv.png',fullPage:false});
await pg.locator('#votoAlm').scrollIntoViewIfNeeded();await pg.screenshot({path:'/tmp/claude-0/-home-user/5853f958-644c-5d2f-baa4-3130bae7435e/scratchpad/voto.png'});
console.log('errores JS:',errs.length?errs:'ninguno');await b.close();
