import { chromium } from 'playwright';
const errs=[], log=(...a)=>console.log(...a);
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2})).newPage();
pg.on('pageerror',e=>errs.push(e.message)); pg.on('console',m=>{if(m.type()==='error'&&!/ERR_FAILED/.test(m.text()))errs.push(m.text())});
await pg.route('**/*',r=>r.request().url().startsWith('file:')?r.continue():r.abort());
await pg.goto('file:///home/user/marea/public/index.html');
await pg.evaluate(()=>{try{localStorage.clear()}catch(e){}}); await pg.reload();
await pg.fill('#lced','100000001'); await pg.fill('#lpin','2026'); await pg.click('#lbtn'); await pg.waitForSelector('.hero');
await pg.click('button[aria-label="Administrar"]'); await pg.click('text=Llenar con IA');
await pg.fill('#in_ia','Casa frente al mar en Same con piscina privada, parrilla, cocina equipada, wifi y aire acondicionado en todas las habitaciones. https://www.airbnb.cl/rooms/49074368');
await pg.click('#in_iab'); await pg.waitForTimeout(300);
log('comodidades:', (await pg.inputValue('#in_amenidades')).replace(/\n/g,', '), '| airbnb:', await pg.inputValue('#in_airbnb_url'));
await pg.setInputFiles('#cfotos input[type=file]',['./v3-02-album.png','./v2-09-dress.png']); await pg.waitForSelector('#cfotos button img');
log('fotos casa en editor:', await pg.locator('#cfotos button img').count());
await pg.click('#sheetBody button.btn.primary.block'); await pg.waitForTimeout(200);
await pg.click('.tab:nth-child(1)'); await pg.waitForSelector('.hero.con-foto'); log('portada en Hoy: sí');
await pg.screenshot({path:'v5-01-hoy-portada.png'});
await pg.click('.esen button >> text=La casa'); await pg.waitForSelector('.casa-g img'); log('galería casa:', await pg.locator('.casa-g img').count(), '| botón airbnb:', await pg.locator('#sheetBody >> text=Ver la casa en Airbnb').count());
await pg.screenshot({path:'v5-02-casa.png'});
log('scrollWidth:', await pg.evaluate(()=>document.documentElement.scrollWidth)); log('ERRORES:', errs.length?errs.join('\n'):'ninguno');
await b.close();
