import { chromium } from 'playwright';
const errs=[], log=(...a)=>console.log(...a);
const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2})).newPage();
pg.on('pageerror',e=>errs.push(e.message)); pg.on('console',m=>{if(m.type()==='error'&&!/ERR_FAILED|ERR_FILE_NOT_FOUND/.test(m.text()))errs.push(m.text())});
await pg.route('**/*',r=>r.request().url().startsWith('file:')?r.continue():r.abort());
await pg.goto('file:///home/user/marea/public/index.html');
await pg.fill('#lced','0990000002');  await pg.click('#lbtn'); await pg.waitForSelector('.hh');
await pg.evaluate(()=>irA('nosotros')); await pg.waitForSelector('text=fotos del viaje');
await pg.setInputFiles('#main input[type=file]',['./v2-02-menu-dia1.png','./v2-08-itinerario.png','./v2-09-dress.png']);
await pg.waitForSelector('#ft_go'); await pg.fill('#ft_t','Pruebas del álbum'); await pg.selectOption('#ft_d',{index:1});
await pg.selectOption('#ft_e',{label:'BBQ & Cocktail Night'}); await pg.screenshot({path:'v3-01-subir.png'});
await pg.click('#ft_go'); await pg.waitForSelector('.alb img');
log('fotos en álbum:', await pg.locator('#main .alb img').count());
log('filtros:', (await pg.$$eval('.chips.scroll .chip',x=>x.map(e=>e.textContent))).join(' | '));
await pg.screenshot({path:'v3-02-album.png'});
await pg.click('.chips.scroll .chip >> text=Día 2'); log('día 2:', await pg.locator('#main .alb img').count());
await pg.click('.chips.scroll .chip >> text=BBQ'); log('noche bbq:', await pg.locator('#main .alb img').count());
await pg.click('#main .alb button >> nth=0'); await pg.waitForSelector('.lb img'); log('visor:', (await pg.locator('#sheetBody .row b').first().textContent()), '|', await pg.locator('#sheetBody p').textContent());
await pg.click('text=Siguiente'); await pg.screenshot({path:'v3-03-visor.png'}); await pg.keyboard.press('Escape');
await pg.click('.tab:nth-child(1)'); log('hoy muestra fotos:', await pg.locator('#main .alb img').count());
await pg.evaluate(()=>irA('nosotros')); await pg.click('text=Viajeros'); await pg.click('.pcard >> nth=1'); log('ficha con fotos:', await pg.locator('#sheetBody .alb img').count()); await pg.keyboard.press('Escape');
// la persona que no subió no puede borrar
await pg.evaluate(()=>salir()); await pg.fill('#lced','0990000005');  await pg.click('#lbtn'); await pg.waitForSelector('.hh');
await pg.evaluate(()=>irA('nosotros')); await pg.click('text=Álbum de fotos'); await pg.click('.chips.scroll .chip >> text=Todas'); await pg.click('#main .alb button >> nth=0'); log('otro invitado ve "Borrar":', await pg.locator('#sheetBody >> text=Borrar foto').count()); await pg.keyboard.press('Escape');
await pg.evaluate(()=>irA('planes')); await pg.waitForSelector('.tl3'); await pg.screenshot({path:'v3-04-itinerario.png'});
await pg.click('text=Mi agenda'); log('mi agenda (eventos):', await pg.locator('.tl3-i').count());
log('scrollWidth:', await pg.evaluate(()=>document.documentElement.scrollWidth)); log('ERRORES:', errs.length?errs.join('\n'):'ninguno');
await b.close();
