import { chromium } from 'playwright';
const errs=[];const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});
const pg=await (await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2})).newPage();pg.on('pageerror',e=>errs.push(e.message));
await pg.route('**/*',r=>{const u=r.request().url();return u.startsWith('file:')||/fonts\.(googleapis|gstatic)/.test(u)?r.continue():r.abort()});
await pg.goto('file:///home/user/marea/public/index.html');await pg.evaluate(()=>{try{localStorage.clear()}catch(e){}});await pg.reload();await pg.waitForTimeout(500);
await pg.fill('#lced','0990000001');await pg.click('#lbtn');await pg.waitForSelector('.hh');await pg.waitForTimeout(500);
await pg.screenshot({path:'z-1-hoy.png'});
await pg.click('.hh-top');await pg.waitForTimeout(500);
const caras=await pg.evaluate(()=>activos().map(p=>nom(p.id)+':'+(caraDe(p)?'sí':'no')).join(' · '));console.log('caras:',caras);
console.log('fotos cargadas en Viajeros:',await pg.evaluate(()=>[...document.querySelectorAll('#main .av img')].filter(i=>i.complete&&i.naturalWidth>0).length));
await pg.screenshot({path:'z-2-viajeros.png'});
await pg.evaluate(()=>abrirPersona(activos().find(p=>p.nombre==='Alegría').id));await pg.waitForTimeout(400);await pg.screenshot({path:'z-3-ficha.png'});
await pg.click('.cara-btn');await pg.waitForTimeout(500);console.log('visor abierto:',await pg.locator('#visorCara.on').count(),'| tamaño foto:',await pg.evaluate(()=>document.querySelector('#visorCara .av').getBoundingClientRect().width));
await pg.screenshot({path:'z-4-grande.png'});
await pg.click('#visorCara');await pg.waitForTimeout(200);console.log('cerrado:',await pg.locator('#visorCara').count()===0,'| ficha sigue:',await pg.evaluate(()=>!document.querySelector('#sheet').hidden));
console.log('errores:',errs.length?errs:'ninguno');await b.close();
