-- v24 · cada evento con su información completa y su lista de qué llevar (Daniel, 7-oct-2026).
-- Idempotente. Solo esquema marea. La descripción se reemplaza solo si está vacía o es más corta que la nueva
-- (la semilla vieja era de una línea); la lista solo se llena si está vacía. Lo que alguien ya llenó se queda.
with nuevo(titulo, descripcion, lista) as (values
  ($q$Llegada y check-in$q$, $q$Llegamos a Casablanca a eso de las 3. Repartimos cuartos, guardamos la despensa en la cocina y las bebidas en los coolers, primer chapuzón en la piscina y foto de llegada en la terraza. A las 7, cena ligera costeña en casa.$q$, $q$[{"txt":"Despensa del primer día","ok":false},{"txt":"Hielo y coolers","ok":false},{"txt":"Toallas de playa","ok":false},{"txt":"Bloqueador","ok":false},{"txt":"Parlante","ok":false}]$q$::jsonb),
  ($q$Círculo de intenciones bajo las estrellas$q$, $q$Welcome White Night: después de la cena bajamos a la playa todos de blanco. Fogata, mantas y velas; una ronda donde cada quien dice qué quiere llevarse de este viaje. Cierra con la primera foto del grupo.$q$, $q$[{"txt":"Leña o carbón para la fogata","ok":false},{"txt":"Encendedor","ok":false},{"txt":"Mantas","ok":false},{"txt":"Velas o lucecitas","ok":false},{"txt":"Parlante con música suave","ok":false}]$q$::jsonb),
  ($q$Yoga matutino$q$, $q$Cuarenta minutos de yoga suave frente al mar, con el sol todavía amable. Nadie tiene que saber: es para estirar y despertar. Después, desayuno internacional con café ilimitado, jugo de naranja, agua de coco y fruta.$q$, $q$[{"txt":"Esteras o toallas grandes","ok":false},{"txt":"Agua","ok":false},{"txt":"Bloqueador","ok":false},{"txt":"Playlist tranquila","ok":false}]$q$::jsonb),
  ($q$Torneo de panzazos en la piscina$q$, $q$Tres jurados con cartelitos del 1 al 10 califican salpicadura, estilo y valentía. Tres rondas; quien gana elige la playlist de la noche. Ojo: la piscina del condominio tiene horario.$q$, $q$[{"txt":"Cartelitos del 1 al 10","ok":false},{"txt":"Marcadores","ok":false},{"txt":"Premio para el ganador","ok":false},{"txt":"Toallas","ok":false}]$q$::jsonb),
  ($q$Pizza & Game Night$q$, $q$En pijama elegante: armamos pizzas caseras entre todos (margarita, pepperoni, prosciutto con rúcula, cuatro quesos y libre) y competimos por la mejor y la peor. Después UNO, Jenga, Pictionary, charadas y Heads Up!; Monopoly y Risk para los valientes.$q$, $q$[{"txt":"Masa y salsa de tomate","ok":false},{"txt":"Quesos y toppings","ok":false},{"txt":"UNO","ok":false},{"txt":"Jenga","ok":false},{"txt":"Pictionary","ok":false},{"txt":"Heads Up!","ok":false}]$q$::jsonb),
  ($q$Spike ball, red y paletas de playa$q$, $q$Red, pelota, paletas y spike ball en la playa. Parejas sorteadas, partidos de 10 minutos y eliminación directa. Los que pierden traen las bebidas de los que ganan.$q$, $q$[{"txt":"Spike ball","ok":false},{"txt":"Red y pelota","ok":false},{"txt":"Paletas","ok":false},{"txt":"Cooler con agua y hielo","ok":false},{"txt":"Bloqueador","ok":false}]$q$::jsonb),
  ($q$BBQ & Cocktail Night$q$, $q$Parrillada en la terraza mientras se esconde el sol: picaña o entraña, pollo, chorizos, mazorcas, maduros y papas, con chimichurri. Barra de cócteles (mojitos, margaritas, cuba libre) y opciones sin alcohol. Foto de grupo cuando el sol toque el mar.$q$, $q$[{"txt":"Carbón","ok":false},{"txt":"Carnes, pollo y chorizos","ok":false},{"txt":"Mazorcas y maduros","ok":false},{"txt":"Chimichurri","ok":false},{"txt":"Ron, tequila y limones","ok":false},{"txt":"Hielo","ok":false}]$q$::jsonb),
  ($q$Karaoke y Talent Show$q$, $q$Después de la parrillada: proyector y dos micrófonos. Primero el karaoke, una canción obligatoria por persona; luego el show, donde cada quien presenta el talento que anotó en su ficha. Hay premio al mejor.$q$, $q$[{"txt":"Proyector","ok":false},{"txt":"Dos micrófonos","ok":false},{"txt":"Parlante","ok":false},{"txt":"Lista de canciones","ok":false},{"txt":"Premio al mejor talento","ok":false}]$q$::jsonb),
  ($q$Sesión de fotos Freaky Monkey$q$, $q$Al atardecer, con las gafas de Freaky Monkey y el look Tiki Boho: fotos de grupo, por parejas y de cerca a las gafas. Cuarenta minutos aprovechando la golden hour.$q$, $q$[{"txt":"Gafas Freaky Monkey","ok":false},{"txt":"Trípode","ok":false},{"txt":"Celulares cargados","ok":false},{"txt":"Collares de flores","ok":false}]$q$::jsonb),
  ($q$Tapas & Wine Night$q$, $q$Gambas al ajillo, patatas bravas, tortilla española, pan con tomate y jamón, croquetas; quesos, embutidos y aceitunas. Vino blanco y tinto Tempranillo o Rioja, con una clase corta de enología. Cierra con la sesión de hipnosis.$q$, $q$[{"txt":"Vino blanco y tinto","ok":false},{"txt":"Quesos y embutidos","ok":false},{"txt":"Pan y tomate","ok":false},{"txt":"Copas","ok":false},{"txt":"Velas","ok":false}]$q$::jsonb),
  ($q$Restaurant Night$q$, $q$La última noche fuera de casa: mesa para ocho frente al mar, un brindis por el viaje y los mejores momentos. Nadie cocina ni lava.$q$, $q$[{"txt":"Reservar mesa para 8","ok":false},{"txt":"Transporte de ida y vuelta","ok":false},{"txt":"Efectivo para la propina","ok":false}]$q$::jsonb),
  ($q$Throwback 2000s$q$, $q$Ropa de la época, reguetón viejo y trivia de la década. Gana quien llegue más fiel a 2005.$q$, $q$[{"txt":"Playlist de los 2000","ok":false},{"txt":"Preguntas de trivia","ok":false}]$q$::jsonb),
  ($q$Cine bajo las estrellas$q$, $q$Proyector afuera entre las palmeras, canguil y mantas; la película se vota en el chat.$q$, $q$[{"txt":"Proyector y sábana blanca","ok":false},{"txt":"Canguil","ok":false},{"txt":"Mantas","ok":false}]$q$::jsonb),
  ($q$Búsqueda del tesoro$q$, $q$Pistas escondidas por la casa y la playa, dos equipos y un premio al final.$q$, $q$[{"txt":"Pistas impresas","ok":false},{"txt":"Premio","ok":false}]$q$::jsonb),
  ($q$Olimpiadas de playa$q$, $q$Vóley, carrera de sacos, relevos con baldes y concurso de castillos de arena.$q$, $q$[{"txt":"Sacos","ok":false},{"txt":"Baldes","ok":false},{"txt":"Pelota de vóley","ok":false}]$q$::jsonb)
)
update marea.eventos e set
  descripcion = case when coalesce(e.descripcion,'') = '' or length(e.descripcion) < length(n.descripcion) then n.descripcion else e.descripcion end,
  lista = case when coalesce(e.lista,'[]'::jsonb) = '[]'::jsonb then n.lista else e.lista end
from nuevo n where e.titulo = n.titulo;
